language: dart

dart:
  - dev


script:
  - pub run test -r expanded
  - dartfmt -n --set-exit-if-changed lib/
  - dartanalyzer --fatal-infos --fatal-warnings .
  #- pub global run test_cov
  #- bash <(curl -s https://codecov.io/bash)
