name: test_cov
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.2.0
homepage: https://github.com/vitusortner/test_cov
authors:
  - Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
  - Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

executables:
  test_cov:

dependencies:
  coverage: ^0.13.3
  path: ^1.6.4
  lcov: ^5.5.0

dev_dependencies:
  test: ^1.11.0
